camunda.base-url=http://127.0.0.1:8080/engine-rest
camunda.process-definition-key=airbnb-fast-booking
camunda.worker-id=airbnb-lab4-worker
camunda.external-task.lock-duration=30000
camunda.external-task.max-tasks=1
camunda.external-task.poll-delay=5000
