spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/blps
spring.datasource.username=postgres
spring.datasource.password=AssA1979
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect