server.port=28082
camunda.base-url=http://127.0.0.1:8080/engine-rest
narayana.log-dir=/home/studs/s408560/narayana-logs
spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=s408560
